# Generated by Django 3.2.24 on 2024-02-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
